services:
  service1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    environment:
      - MATLAB_RUNTIME=/opt/v94
